#!/usr/bin/env python3
"""Regenerate docs/rules.md from the rule packs.

A hand-maintained rule catalogue is wrong within a week. This reads the packs
and the scanner metadata, so the document cannot drift from the code.

    python3 tools/generate_rule_docs.py          # write docs/rules.md
    python3 tools/generate_rule_docs.py --check  # fail if it is out of date
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import Counter, defaultdict
from typing import Dict, List

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "engine"))

from redassay import severity as sev            # noqa: E402
from redassay.rules import load_all             # noqa: E402
from redassay.scanners.python_ast import RULES as AST_RULES   # noqa: E402
from redassay.scanners.javascript import SINKS, STATIC_RULES  # noqa: E402
from redassay.scanners.php import SINKS as PHP_SINKS          # noqa: E402
from redassay.scanners.registry import describe  # noqa: E402

TARGET = os.path.join(ROOT, "docs", "rules.md")


def _unique_php():
    """PHP sinks, one row per rule id (some ids have several patterns)."""
    seen = set()
    rows = []
    for rule_id, category, pattern, meta in PHP_SINKS:
        if rule_id in seen:
            continue
        seen.add(rule_id)
        rows.append((rule_id, category, pattern, meta))
    return rows

PACK_BLURBS = {
    "injection": "Untrusted data reaching an interpreter: SQL, shells, the language itself, templates, LDAP, XPath, NoSQL.",
    "xss": "Untrusted data reaching an HTML parser, across DOM APIs, frameworks and server-side templates.",
    "deserialization": "Formats that reconstruct objects, and therefore execute code, from bytes you did not write.",
    "crypto": "Algorithms, modes, key material and comparisons that do not provide the property they appear to.",
    "access-control": "Who is allowed to do what: path confinement, object ownership, CORS, CSRF, authorization placement.",
    "ssrf": "The server making requests on an attacker's behalf, and redirects that hand your domain to a phishing page.",
    "secrets-config": "Application, container and cloud configuration that is permissive by default or by accident.",
    "jvm": "Java, Kotlin and Scala: exec, JDBC, SpEL, XML factories, trust managers, Spring Security.",
    "golang": "Go: query construction, TLS, math/rand, discarded errors from verification calls.",
    "php-ruby": "PHP superglobals reaching dangerous sinks, and Ruby's dynamic dispatch and mass assignment.",
    "api-mobile": "API surface and mobile manifests: GraphQL, rate limiting, error verbosity, exported components.",
    "exposure": "Information that leaks out sideways: credentials and personal data in logs, diagnostic endpoints, tracebacks in responses, privileged actions with no audit trail.",
}


def render() -> str:
    rules = load_all()
    by_pack: Dict[str, List[dict]] = defaultdict(list)
    for rule in rules:
        by_pack[rule.get("pack", "other")].append(rule)

    severities = Counter(r.get("severity", "medium") for r in rules)
    cwes = {c for r in rules for c in (r.get("cwe") or [])}

    out: List[str] = []
    out.append("# Rule catalogue")
    out.append("")
    out.append("<!-- Generated by tools/generate_rule_docs.py. Do not edit by hand. -->")
    out.append("")
    out.append(
        f"{len(rules)} pattern rules across {len(by_pack)} packs, plus "
        f"{len(AST_RULES)} Python AST rules, {len(SINKS) + len(STATIC_RULES)} "
        f"JavaScript rules, and {len(_unique_php())} PHP taint sinks that need "
        "more than a pattern match."
    )
    out.append("")
    out.append("| Severity | Rules |")
    out.append("| --- | --- |")
    for name in sev.ORDER:
        if severities.get(name):
            out.append(f"| {name} | {severities[name]} |")
    out.append("")
    out.append(f"Covering {len(cwes)} distinct CWEs.")
    out.append("")

    out.append("## Scanners")
    out.append("")
    out.append("| Scanner | What it does |")
    out.append("| --- | --- |")
    for entry in describe():
        out.append(f"| `{entry['name']}` | {entry['description']} |")
    out.append("")

    out.append("## Pattern rule packs")
    out.append("")
    for pack in sorted(by_pack):
        items = sorted(by_pack[pack], key=lambda r: (sev.rank(r.get("severity")), r["id"]))
        out.append(f"### {pack}")
        out.append("")
        blurb = PACK_BLURBS.get(pack)
        if blurb:
            out.append(blurb)
            out.append("")
        out.append("| Rule | Severity | Languages | CWE |")
        out.append("| --- | --- | --- | --- |")
        for rule in items:
            languages = ", ".join(rule.get("languages") or ["all"])
            if len(languages) > 42:
                languages = languages[:39] + "..."
            out.append(
                f"| `{rule['id']}`<br>{rule['title']} "
                f"| {rule.get('severity', 'medium')} "
                f"| {languages} "
                f"| {', '.join(rule.get('cwe') or [])} |"
            )
        out.append("")

    out.append("## Python AST rules")
    out.append("")
    out.append(
        "These parse the file rather than matching text. Findings with confirmed "
        "taint are raised a severity level; findings the function already guards "
        "are lowered one and marked low confidence."
    )
    out.append("")
    out.append("| Rule | Severity | What it means |")
    out.append("| --- | --- | --- |")
    for rule_id, meta in sorted(AST_RULES.items(), key=lambda kv: (sev.rank(kv[1]["severity"]), kv[0])):
        out.append(f"| `{rule_id}` | {meta['severity']} | {meta['title']} |")
    out.append("")

    out.append("## JavaScript rules")
    out.append("")
    out.append(
        "Taint sinks fire only when a value bound out of `req.query`, `req.body` "
        "or `req.params` reaches them. Static rules match a literal pattern."
    )
    out.append("")
    out.append("| Rule | Severity | Kind |")
    out.append("| --- | --- | --- |")
    for rule_id, _pattern, meta in SINKS:
        out.append(f"| `{rule_id}` | {meta['severity']} | taint sink |")
    for rule_id, _pattern, meta in STATIC_RULES:
        out.append(f"| `{rule_id}` | {meta['severity']} | static |")
    out.append("")

    out.append("## PHP rules")
    out.append("")
    out.append(
        "The PHP taint scanner traces request data (`$_GET`, `$_POST`, "
        "`$_REQUEST`, `$_COOKIE`, `$_FILES`, request-derived `$_SERVER` keys, "
        "`php://input`) through variables to a sink, over a template-aware "
        "normalized view. A finding means a concrete assignment-to-sink path, "
        "not a pattern hit."
    )
    out.append("")
    out.append("| Rule | Severity | Kind |")
    out.append("| --- | --- | --- |")
    for rule_id, _category, _pattern, meta in _unique_php():
        out.append(f"| `{rule_id}` | {meta['severity']} | taint sink |")
    out.append("")

    out.append("## Suppressing a rule")
    out.append("")
    out.append("In the source, with the reason next to the code it excuses:")
    out.append("")
    out.append("```python")
    out.append("# redassay: ignore py.shell-dynamic - the command is a module constant")
    out.append("subprocess.run(BACKUP_COMMAND, shell=True)")
    out.append("```")
    out.append("")
    out.append("Across a path:")
    out.append("")
    out.append("```bash")
    out.append('redassay suppress crypto.md5-sha1-usage --path "cache/**" --reason "content fingerprints"')
    out.append("```")
    out.append("")
    out.append("Or for the whole repository, committed in `pyproject.toml`:")
    out.append("")
    out.append("```toml")
    out.append("[tool.redassay]")
    out.append('disabled_rules = ["authz.missing-authorization-check"]')
    out.append("```")
    out.append("")
    out.append("See [writing-rules.md](writing-rules.md) to add or override one.")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if docs/rules.md is stale")
    args = parser.parse_args()

    content = render()
    if args.check:
        try:
            with open(TARGET, "r", encoding="utf-8") as handle:
                current = handle.read()
        except OSError:
            current = ""
        if current != content:
            print("docs/rules.md is out of date - run tools/generate_rule_docs.py")
            return 1
        print("docs/rules.md is current")
        return 0

    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
